/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_UNIT_TEST_SIMPLE_PB_H_INCLUDED
#define PB_UNIT_TEST_SIMPLE_PB_H_INCLUDED
#include "app/nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(4) student_t_array8_t;
typedef struct _student_t {
    /* reserved id 1 3 4 */
    uint32_t id;
    char name[5];
    /* reserved */
    student_t_array8_t array8; /* pb_size_t size; pb_byte_t bytes[n]; */
    pb_byte_t fix_array8[4]; /* pb_byte_t fix_array8[16]; */
    pb_size_t array32_count;
    uint32_t array32[4]; /* pb_size_t array32_count; uint32_t array32[5]; */
    uint32_t fix_array32[4]; /* uint32_t fix_array32[5]; */
    char str[9]; /* char str[41]; */
} student_t;

typedef PB_BYTES_ARRAY_T(4) teacher_t_array8_t;
typedef struct _teacher_t {
    /* reservedid 1 3 4 */
    uint32_t id;
    /* reserved */
    teacher_t_array8_t array8; /* pb_size_t size; pb_byte_t bytes[n]; */
    pb_byte_t fix_array8[4]; /* pb_byte_t fix_array8[16]; */
    pb_size_t array32_count;
    uint32_t array32[4]; /* pb_size_t array32_count; uint32_t array32[5]; */
    uint32_t fix_array32[4]; /* uint32_t fix_array32[5]; */
    char str[9]; /* char str[41]; */
} teacher_t;

typedef struct _person_t {
    pb_size_t student_count;
    student_t student[2]; /* pb_size_t sutdent_count;simple_student_t sutdent[16]; */
    bool has_teacher;
    teacher_t teacher;
} person_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define student_t_init_default                   {0, "", {0, {0}}, {0}, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, ""}
#define teacher_t_init_default                   {0, {0, {0}}, {0}, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, ""}
#define person_t_init_default                    {0, {student_t_init_default, student_t_init_default}, false, teacher_t_init_default}
#define student_t_init_zero                      {0, "", {0, {0}}, {0}, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, ""}
#define teacher_t_init_zero                      {0, {0, {0}}, {0}, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, ""}
#define person_t_init_zero                       {0, {student_t_init_zero, student_t_init_zero}, false, teacher_t_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define student_t_id_tag                         5
#define student_t_name_tag                       6
#define student_t_array8_tag                     9
#define student_t_fix_array8_tag                 10
#define student_t_array32_tag                    11
#define student_t_fix_array32_tag                12
#define student_t_str_tag                        13
#define teacher_t_id_tag                         5
#define teacher_t_array8_tag                     9
#define teacher_t_fix_array8_tag                 10
#define teacher_t_array32_tag                    11
#define teacher_t_fix_array32_tag                12
#define teacher_t_str_tag                        13
#define person_t_student_tag                     2
#define person_t_teacher_tag                     3

/* Struct field encoding specification for nanopb */
#define student_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                5) \
X(a, STATIC,   SINGULAR, STRING,   name,              6) \
X(a, STATIC,   SINGULAR, BYTES,    array8,            9) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, fix_array8,       10) \
X(a, STATIC,   REPEATED, UINT32,   array32,          11) \
X(a, STATIC,   FIXARRAY, UINT32,   fix_array32,      12) \
X(a, STATIC,   SINGULAR, STRING,   str,              13)
#define student_t_CALLBACK NULL
#define student_t_DEFAULT NULL

#define teacher_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                5) \
X(a, STATIC,   SINGULAR, BYTES,    array8,            9) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, fix_array8,       10) \
X(a, STATIC,   REPEATED, UINT32,   array32,          11) \
X(a, STATIC,   FIXARRAY, UINT32,   fix_array32,      12) \
X(a, STATIC,   SINGULAR, STRING,   str,              13)
#define teacher_t_CALLBACK NULL
#define teacher_t_DEFAULT NULL

#define person_t_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  student,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teacher,           3)
#define person_t_CALLBACK NULL
#define person_t_DEFAULT NULL
#define person_t_student_MSGTYPE student_t
#define person_t_teacher_MSGTYPE teacher_t

extern const pb_msgdesc_t student_t_msg;
extern const pb_msgdesc_t teacher_t_msg;
extern const pb_msgdesc_t person_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define student_t_fields &student_t_msg
#define teacher_t_fields &teacher_t_msg
#define person_t_fields &person_t_msg

/* Maximum encoded size of messages (where known) */
#define person_t_size                            246
#define student_t_size                           82
#define teacher_t_size                           76

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
