/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "simple.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(student_t, student_t, AUTO)


PB_BIND(teacher_t, teacher_t, AUTO)


PB_BIND(person_t, person_t, AUTO)



